//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkSpider3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkSpider3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This Source Code Form is subject to the terms of the Mozilla Public
        ///// License, v. 2.0. If a copy of the MPL was not distributed with this
        ///// file, You can obtain one at http://mozilla.org/MPL/2.0/.
        ///
        ///// ===BEGIN ICANN DOMAINS===
        ///
        ///// ac : http://en.wikipedia.org/wiki/.ac
        ///ac
        ///com.ac
        ///edu.ac
        ///gov.ac
        ///net.ac
        ///mil.ac
        ///org.ac
        ///
        ///// ad : http://en.wikipedia.org/wiki/.ad
        ///ad
        ///nom.ad
        ///
        ///// ae : http://en.wikipedia.org/wiki/.ae
        ///// see also: &quot;Domain Name Eligibility Policy&quot; at http://www.aeda.ae/eng/aepolicy.php
        ///ae
        ///co.ae
        ///net.a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string effective_tld_names_dat {
            get {
                return ResourceManager.GetString("effective_tld_names_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,google.com
        ///2,facebook.com
        ///3,youtube.com
        ///4,yahoo.com
        ///5,baidu.com
        ///6,wikipedia.org
        ///7,live.com
        ///8,twitter.com
        ///9,qq.com
        ///10,amazon.com
        ///11,blogspot.com
        ///12,google.co.in
        ///13,linkedin.com
        ///14,taobao.com
        ///15,sina.com.cn
        ///16,yahoo.co.jp
        ///17,msn.com
        ///18,google.com.hk
        ///19,wordpress.com
        ///20,google.de
        ///21,google.co.jp
        ///22,ebay.com
        ///23,google.co.uk
        ///24,yandex.ru
        ///25,babylon.com
        ///26,googleusercontent.com
        ///27,google.fr
        ///28,bing.com
        ///29,163.com
        ///30,weibo.com
        ///31,microsoft.com
        ///32,google.com.br
        ///33,tumblr.com
        ///34,mail.ru
        ///35,t.co
        ///36,vk.com
        ///37,soso.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string top_1m {
            get {
                return ResourceManager.GetString("top_1m", resourceCulture);
            }
        }
    }
}
